CREATE DATABASE customer_behavior;
USE customer_behavior;

SELECT * FROM customer LIMIT 20;

-- Business Problems -- 

-- Q1 What is the total revenue generated by male v/s female customer ?
SELECT * FROM customer;
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
ORDER BY revenue;

-- Q2. Which customer used a discount but still spend more than the average purchase amount? -- 
SELECT * FROM customer;
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = "Yes" AND purchase_amount >= (SELECT AVG(purchase_amount) AS avg_purchase_amount FROM customer);

-- Q3. Which are the top 5 products with highest average review rating

SELECT item_purchased, ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amount between standard and express shipping -- 
SELECT * FROM customer;
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amt
FROM customer
WHERE shipping_type IN("Express" , "Standard")
GROUP BY shipping_type
ORDER BY avg_purchase_amt;

-- Q5. Do subcribed customer spend more? Compare average spend and total revenue between subcriber & non subcriber.
SELECT * FROM customer;
SELECT COUNT(customer_id) AS total_customer,
	subscription_status,
	 AVG(purchase_amount) AS average_spend, SUM(purchase_amount) AS  total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY average_spend, total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchase with discount applied ? --
-- SELECT * FROM customer;
-- SELECT percent_rank(item_purchased) AS  percentag_purchase

-- Q7. Segment customer into New, Returning and loyal based on their total no of previous purchase and show the count of each segment -- 
SELECT * FROM customer;
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10  THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) AS "Number of Customer"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchase products within each category ? -- 
WITH item_count AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ? -- 
SELECT * FROM customer;
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE purchase_amount > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group ? -- 
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;